title: "[Discussion] "

body:
  - type: checkboxes
    id: attendees
    attributes:
      label: ✅ 회의 참석자 체크리스트
      options:
        - label: 김동훈
        - label: 이강욱
        - label: 김용준
        - label: 김동현
        - label: 배정현

  - type: textarea
    id: discussion-topic
    attributes:
      label: 💡 논의 주제
      placeholder: 논의할 주제를 작성해주세요.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🤔 해야할 일

  - type: textarea
    id: task-kim-donghoon
    attributes:
      label: 김동훈
      placeholder: 김동훈님이 해야 할 일을 작성해주세요.
    validations:
      required: false

  - type: textarea
    id: task-lee-ganguk
    attributes:
      label: 이강욱
      placeholder: 이강욱님이 해야 할 일을 작성해주세요.
    validations:
      required: false

  - type: textarea
    id: task-kim-yongjun
    attributes:
      label: 김용준
      placeholder: 김용준님이 해야 할 일을 작성해주세요.
    validations:
      required: false

  - type: textarea
    id: task-kim-donghyun
    attributes:
      label: 김동현
      placeholder: 김동현님이 해야 할 일을 작성해주세요.
    validations:
      required: false

  - type: textarea
    id: task-bae-jeonghyeon
    attributes:
      label: 배정현
      placeholder: 배정현님이 해야 할 일을 작성해주세요.
    validations:
      required: false
