spring:
  datasource:
    url: jdbc:mysql://localhost:3307/lms_loadtest?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: loadtest
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
