spring:
  application:
    name: Code-Bomba-LMS
  profiles:
    active: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000


#챗봇설정
fastapi:
  url: http://localhost:8000

chat:
  max-history-messages: 20