### 로그인 (쿠키 저장)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "u01@test.com",
  "password": "Test1234!"
}

###
### 채팅방 목록 조회
GET http://localhost:8080/api/v1/chat/list

###
### 메시지 목록 조회 (roomId = 16)
GET http://localhost:8080/api/v1/chat/16/messages

###
### 메시지 전송 (roomId = 16)
POST http://localhost:8080/api/v1/chat/16/messages
Content-Type: application/json

{
  "userMessage": "이 문제를 어떻게 풀어야 하나요?"
}

###
### 채팅방 생성
POST http://localhost:8080/api/v1/chat
Content-Type: application/json

{
  "problemSetId": 3001
}


###
### 채팅방 삭제 (roomId = 1)
DELETE http://localhost:8080/api/v1/chat/1
