@baseUrl = http://localhost:8080
@categoryId = 2001
@problemSetId = 2001
@completedProblemSetId = 2001
@codeProblemSetId = 3001
@codeProblemId = 3001
@connectedDatasetId = 3001
@textProblemId = 2001
@userId = 4
@completedUserId = 3
@manageProblemSetId = 2002

### 1. 移댄뀒怨좊━ 紐⑸줉 議고쉶
GET {{baseUrl}}/api/v1/problem-categories
Accept: application/json


### 2. 臾몄젣 ?명듃 紐⑸줉 議고쉶
GET {{baseUrl}}/api/v1/problem-sets?categoryId={{categoryId}}
Accept: application/json


### 3. 臾몄젣 ?명듃 紐⑸줉 議고쉶 ?ㅽ뙣 - ?녿뒗 移댄뀒怨좊━
GET {{baseUrl}}/api/v1/problem-sets?categoryId=999999
Accept: application/json


### 4. 臾몄젣 ?명듃 吏꾩엯 - 吏꾪뻾 以??ъ슜??
GET {{baseUrl}}/api/v1/problem-sets/{{problemSetId}}?userId={{userId}}
Accept: application/json


### 5. 臾몄젣 ?명듃 吏꾩엯 - ?꾨즺 ?ъ슜??
GET {{baseUrl}}/api/v1/problem-sets/{{completedProblemSetId}}?userId={{completedUserId}}
Accept: application/json


### 6. 肄붾뱶 臾몄젣 ?명듃 吏꾩엯 - ?쒖옉 肄붾뱶 ?뺤씤
GET {{baseUrl}}/api/v1/problem-sets/{{codeProblemSetId}}?userId={{userId}}
Accept: application/json


### 7. 臾몄젣 ?명듃 吏꾩엯 ?ㅽ뙣 - ?녿뒗 臾몄젣 ?명듃
GET {{baseUrl}}/api/v1/problem-sets/999999?userId={{userId}}
Accept: application/json


### 8. 吏꾪뻾 ?곹깭 議고쉶 - 吏꾪뻾 以??ъ슜??
GET {{baseUrl}}/api/v1/problem-sets/{{problemSetId}}/progress?userId={{userId}}
Accept: application/json


### 9. 吏꾪뻾 ?곹깭 議고쉶 - ?꾨즺 ?ъ슜??
GET {{baseUrl}}/api/v1/problem-sets/{{completedProblemSetId}}/progress?userId={{completedUserId}}
Accept: application/json


### 10. 吏꾪뻾 ?곹깭 議고쉶 ?ㅽ뙣 - ?녿뒗 臾몄젣 ?명듃
GET {{baseUrl}}/api/v1/problem-sets/999999/progress?userId={{userId}}
Accept: application/json


### 11. 寃곌낵 議고쉶 - ?꾨즺 ?ъ슜??
GET {{baseUrl}}/api/v1/problem-sets/{{completedProblemSetId}}/result?userId={{completedUserId}}
Accept: application/json


### 12. 寃곌낵 議고쉶 ?ㅽ뙣 - 誘몄셿猷??ъ슜??
GET {{baseUrl}}/api/v1/problem-sets/{{problemSetId}}/result?userId={{userId}}
Accept: application/json


### 13. 寃곌낵 議고쉶 ?ㅽ뙣 - ?녿뒗 臾몄젣 ?명듃
GET {{baseUrl}}/api/v1/problem-sets/999999/result?userId={{userId}}
Accept: application/json


### 14. ?곗씠?곗뀑 ?낅줈??
# 16踰덉뿉???ъ슜?????곗씠?곗뀑???앹꽦?⑸땲??
POST {{baseUrl}}/api/v1/problem-datasets
Accept: application/json
Content-Type: multipart/form-data; boundary=datasetBoundary

--datasetBoundary
Content-Disposition: form-data; name="datasetFile"; filename="clean_architecture_dataset.csv"
Content-Type: text/csv

id,value
1,100
2,200
--datasetBoundary--

> {%
    client.global.set("cleanArchitectureDatasetId", response.body.data.datasetId);
%}


### 15. ?곗씠?곗뀑 ?낅줈???ㅽ뙣 - CSV媛 ?꾨땶 ?뚯씪
POST {{baseUrl}}/api/v1/problem-datasets
Accept: application/json
Content-Type: multipart/form-data; boundary=invalidDatasetBoundary

--invalidDatasetBoundary
Content-Disposition: form-data; name="datasetFile"; filename="clean_architecture_dataset.txt"
Content-Type: text/plain

not,csv,file
--invalidDatasetBoundary--


### 16. 臾몄젣-?곗씠?곗뀑 ?곌껐
# ?ъ쟾 議곌굔: 14踰덉쓣 癒쇱? ?ㅽ뻾?댁꽌 cleanArchitectureDatasetId媛 ?덉뼱???⑸땲??
POST {{baseUrl}}/api/v1/problems/{{codeProblemId}}/datasets
Accept: application/json
Content-Type: application/json

{
  "datasetId": {{cleanArchitectureDatasetId}}
}


### 17. 臾몄젣-?곗씠?곗뀑 ?곌껐 ?ㅽ뙣 - ?대? ?곌껐???곗씠?곗뀑
# ?ъ쟾 議곌굔: 16踰덉쓣 癒쇱? ?ㅽ뻾?댁꽌 媛숈? ?곗씠?곗뀑???대? ?곌껐???곹깭?ъ빞 ?⑸땲??
POST {{baseUrl}}/api/v1/problems/{{codeProblemId}}/datasets
Accept: application/json
Content-Type: application/json

{
  "datasetId": {{cleanArchitectureDatasetId}}
}


### 18-1. ?띿뒪??臾몄젣 ?곌껐 ?ㅽ뙣 ?뚯뒪?몄슜 ?곗씠?곗뀑 ?낅줈??
POST {{baseUrl}}/api/v1/problem-datasets
Accept: application/json
Content-Type: multipart/form-data; boundary=textProblemDatasetBoundary

--textProblemDatasetBoundary
Content-Disposition: form-data; name="datasetFile"; filename="text_problem_dataset.csv"
Content-Type: text/csv

id,value
1,100
--textProblemDatasetBoundary--

> {%
    client.global.set("textProblemDatasetId", response.body.data.datasetId);
%}


### 18. 臾몄젣-?곗씠?곗뀑 ?곌껐 ?ㅽ뙣 - 肄붾뱶 臾몄젣媛 ?꾨떂
POST {{baseUrl}}/api/v1/problems/{{textProblemId}}/datasets
Accept: application/json
Content-Type: application/json

{
  "datasetId": {{textProblemDatasetId}}
}


### 19. 臾몄젣 ?명듃 ?깅줉
POST {{baseUrl}}/api/v1/problems
Accept: application/json
Content-Type: application/json

{
  "title": "?대┛ ?꾪궎?띿쿂 ?깅줉 ?뚯뒪??,
  "categoryName": "?대┛ ?꾪궎?띿쿂",
  "description": "?⑦궎吏 由ы뙥?좊쭅 ???깅줉 ?먮쫫???뺤씤?섎뒗 臾몄젣 ?명듃?낅땲??",
  "dataFileName": null,
  "problems": [
    {
      "title": "怨꾩링 梨낆엫",
      "content": "Controller媛 吏곸젒 ?몄텧?섏? ?딄퀬 ?섏〈?댁빞 ?섎뒗 怨꾩링? 臾댁뾿?멸???",
      "startCode": null,
      "answer": "UseCase",
      "hint": "Application 怨꾩링???낃뎄?낅땲??",
      "explanation": "Controller???붿껌??Command??Query濡?諛붽씀怨?UseCase瑜??몄텧?⑸땲??"
    }
  ]
}


### 20. 臾몄젣 ?명듃 ?섏젙
POST {{baseUrl}}/api/v1/problems
Accept: application/json
Content-Type: application/json

{
  "title": "?섏젙 ?뚯뒪?몄슜 臾몄젣 ?명듃",
  "categoryName": "?곗씠??遺꾩꽍",
  "description": "20踰??섏젙 ?붿껌?먯꽌 ?ъ슜??臾몄젣 ?명듃?낅땲??",
  "dataFileName": null,
  "problems": [
    {
      "title": "?섏젙 ??臾몄젣",
      "content": "?섏젙 ???댁슜?낅땲??",
      "startCode": null,
      "answer": "?섏젙 ???뺣떟",
      "hint": "?섏젙 ???뚰듃",
      "explanation": "?섏젙 ???댁꽕"
    }
  ]
}

> {%
    client.global.set("createdProblemSetId", response.body.data.problemSetId);
%}


### 20-1. 臾몄젣 ?명듃 ?섏젙
# 二쇱쓽: ?꾩옱 ?섏젙 API??problemId媛 ?꾩슂?섎?濡? ?ㅼ젣 ?뺤씤? 湲곗〈 ?붾? ?곗씠??manageProblemSetId瑜??ъ슜?⑸땲??
PUT {{baseUrl}}/api/v1/problems/{{manageProblemSetId}}
Accept: application/json
Content-Type: application/json

{
  "title": "吏묎퀎? 吏??遺꾩꽍 - ?대┛ 援ъ“ ?섏젙",
  "categoryName": "?곗씠??遺꾩꽍",
  "description": "?섏젙 API 由ы뙥?좊쭅 ?뺤씤 ?붿껌?낅땲??",
  "dataFileName": null,
  "problems": [
    {
      "problemId": 2004,
      "title": "GROUP BY 紐⑹쟻 - ?섏젙",
      "content": "SQL?먯꽌 GROUP BY瑜??ъ슜?섎뒗 紐⑹쟻???묒꽦?섏꽭??",
      "startCode": null,
      "answer": "吏묎퀎",
      "hintId": 2004,
      "hint": "吏묎퀎 ?⑥닔? ?④퍡 ?먯＜ ?ъ슜?⑸땲??",
      "explanation": "GROUP BY???뱀젙 而щ읆 湲곗??쇰줈 ?곗씠?곕? 臾띠뼱 吏묎퀎?????ъ슜?⑸땲??"
    }
  ]
}


### 21. 臾몄젣 ?명듃 ??젣 ?ㅽ뙣 - ?쒖텧 湲곕줉 議댁옱
DELETE {{baseUrl}}/api/v1/problems/2001
Accept: application/json


### 22. 臾몄젣 ?명듃 媛뺤젣 鍮꾪솢?깊솕
# 二쇱쓽: ?ㅽ뻾?섎㈃ ?붾? ?곗씠???곹깭媛 INACTIVE濡?諛붾앸땲??
DELETE {{baseUrl}}/api/v1/problems/2001?force=true
Accept: application/json
