### Base URL
@host = http://localhost:8080

### Test IDs
@courseId = 101
@courseCategoryId = 1


### 1. Course category list
GET {{host}}/api/v1/course-categories


### 2. Course list
GET {{host}}/api/v1/courses


### 3. Course list by category
GET {{host}}/api/v1/courses?courseCategoryId={{courseCategoryId}}


### 4. Create course
POST {{host}}/api/v1/courses
Content-Type: application/json

{
  "instructorId": 1,
  "courseCategoryId": {{courseCategoryId}},
  "title": "Java 기초 강좌",
  "description": "Java 기초 문법을 학습하는 강좌입니다.",
  "thumbnailUrl": "java.png"
}


### 5. Course detail
GET {{host}}/api/v1/courses/{{courseId}}


### 6. Update course
PUT {{host}}/api/v1/courses/{{courseId}}
Content-Type: application/json

{
  "courseCategoryId": {{courseCategoryId}},
  "title": "수정된 Java 강좌",
  "description": "수정된 강좌 설명입니다.",
  "thumbnailUrl": "updated-java.png",
  "status": "INACTIVE"
}


### 7. Publish course
PATCH {{host}}/api/v1/courses/{{courseId}}/publish


### 8. Delete course
DELETE {{host}}/api/v1/courses/{{courseId}}


### 9. Check deleted course detail
GET {{host}}/api/v1/courses/{{courseId}}
