### Base URL
@host = http://localhost:8080

### Test IDs
@courseId = 101
@userId = 1
@enrollmentId = 1


### 1. Enroll course
POST {{host}}/api/v1/courses/{{courseId}}/enrollments
Content-Type: application/json

{
  "userId": {{userId}},
  "courseId": {{courseId}}
}


### 2. Check duplicate enrollment
POST {{host}}/api/v1/courses/{{courseId}}/enrollments
Content-Type: application/json

{
  "userId": {{userId}},
  "courseId": {{courseId}}
}


### 3. My enrolled courses
GET {{host}}/api/v1/students/{{userId}}/enrollments


### 4. Cancel enrollment
DELETE {{host}}/api/v1/students/{{userId}}/enrollments/{{enrollmentId}}


### 5. My enrolled courses after cancellation
GET {{host}}/api/v1/students/{{userId}}/enrollments


### 6. Check canceling already canceled enrollment
DELETE {{host}}/api/v1/students/{{userId}}/enrollments/{{enrollmentId}}
